/**
 You are given two strings s and t.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Return the letter that was added to t.

  

 Example 1:
 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 
 Example 2:
 Input: s = "", t = "y"
 Output: "y"
  

 Constraints:
 - 0 <= s.length <= 1000
 - t.length == s.length + 1
 - s and t consist of lowercase English letters.
 */
class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        guard !s.isEmpty else { return t.last! }
        var tStr = t
        for c1 in s {
            for (i, c2) in tStr.enumerated() {
                if c2 == c1 {
                    tStr.remove(at: tStr.index(tStr.startIndex, offsetBy: i))
                    break
                }
            }
        }
        return tStr.last!
    }
}

let s = Solution()
let r = s.findTheDifference("bca", "ucab")
print(r)
